version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=store
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data