name: Pavlo_Polyak

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  nginx:
    build: nginx/
    ports:
        - "883:80"
    depends_on:
      python:
        condition: service_healthy
    volumes: 
       - ./html:/opt/app/

  spring:
    config:
      activate:
        on-profile: prod
  name: prod-YAML
  environment: production
  enabled: true
  servers:
      - www.store.com
      - www.webstore.com

  python:
    runs-on: ubuntu-latest
    needs: [ubuntu]
    strategy:
      matrix:
        python-version:
        - 'pypy-3.7-v7.3.3' # Python 3.7 and PyPy 7.3.3
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: docker build
      run: docker-compose up -d --force-recreate
        
    - name: Create ZIP artifacts
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

    - name: git push
      run: |
       git config --global user.email "poliyakpavlo@gmail.com"
       git config --global user.name "PolyakPavlo" 
       git add ${{ env.DEPLOY_PACKAGE_NAME }}
       git commit -m "logparser"
       git status
       git push
      
#     - name: CleanUp
#       run: |
#         rm -r ~/.ssh